//go:build windows

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	hostsMarkerBegin = "# >>> GoAMPP managed hosts BEGIN — do not edit this block <<<"
	hostsMarkerEnd   = "# <<< GoAMPP managed hosts END >>>"

	apacheMarkerBegin = "# >>> GoAMPP managed Apache vhosts BEGIN <<<"
	apacheMarkerEnd   = "# <<< GoAMPP managed Apache vhosts END >>>"
)

func DefaultHostsFile() string {
	sysRoot := os.Getenv("SystemRoot")
	if sysRoot == "" {
		sysRoot = `C:\Windows`
	}
	return filepath.Join(sysRoot, "System32", "drivers", "etc", "hosts")
}

func ApplyVhosts(baseDir string, cfg *Config) error {
	enabled := make([]Vhost, 0, len(cfg.Vhosts))
	for _, v := range cfg.Vhosts {
		if v.Enabled {
			enabled = append(enabled, v)
		}
	}

	hostsPath := cfg.Settings.HostsFile
	if hostsPath == "" {
		hostsPath = DefaultHostsFile()
	} else {
		hostsPath = ExpandPath(hostsPath, baseDir)
	}
	if err := writeHostsBlock(hostsPath, enabled); err != nil {
		return fmt.Errorf("hosts file: %w", err)
	}

	if p := ExpandPath(cfg.Settings.ApacheVhostsInclude, baseDir); p != "" {
		if err := writeApacheVhosts(p, baseDir, enabled); err != nil {
			return fmt.Errorf("apache vhosts: %w", err)
		}
	}

	if p := ExpandPath(cfg.Settings.NginxSitesDir, baseDir); p != "" {
		if err := writeNginxSites(p, baseDir, enabled); err != nil {
			return fmt.Errorf("nginx sites: %w", err)
		}
	}
	return nil
}

func writeHostsBlock(path string, vhosts []Vhost) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	cleaned := stripManagedBlock(existing, hostsMarkerBegin, hostsMarkerEnd)

	var buf bytes.Buffer
	buf.Write(cleaned)
	if len(cleaned) > 0 && !bytes.HasSuffix(cleaned, []byte("\n")) {
		buf.WriteString("\r\n")
	}
	buf.WriteString(hostsMarkerBegin + "\r\n")
	for _, v := range vhosts {

		fmt.Fprintf(&buf, "127.0.0.1 %s\r\n", v.Domain)
		fmt.Fprintf(&buf, "::1       %s\r\n", v.Domain)
	}
	buf.WriteString(hostsMarkerEnd + "\r\n")

	return atomicWrite(path, buf.Bytes())
}

func writeApacheVhosts(path, baseDir string, vhosts []Vhost) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	defaultDocRoot := strings.ReplaceAll(
		filepath.Join(baseDir, "www"), `\`, `/`)

	var buf bytes.Buffer
	buf.WriteString(apacheMarkerBegin + "\r\n")
	buf.WriteString("# Generated by GoAMPP — edits inside this file will be overwritten.\r\n\r\n")

	fmt.Fprintf(&buf, "<VirtualHost *:80>\r\n")
	fmt.Fprintf(&buf, "    ServerName localhost\r\n")
	fmt.Fprintf(&buf, "    DocumentRoot \"%s\"\r\n", defaultDocRoot)
	fmt.Fprintf(&buf, "    <Directory \"%s\">\r\n", defaultDocRoot)
	buf.WriteString("        Options Indexes FollowSymLinks\r\n")
	buf.WriteString("        AllowOverride All\r\n")
	buf.WriteString("        Require all granted\r\n")
	buf.WriteString("    </Directory>\r\n")
	buf.WriteString("</VirtualHost>\r\n\r\n")

	for _, v := range vhosts {
		if v.ServerType != "" && v.ServerType != "apache" && v.ServerType != "both" {
			continue
		}
		if !v.Enabled {
			continue
		}
		port := v.Port
		if port == 0 {
			port = 80
		}

		fmt.Fprintf(&buf, "<VirtualHost *:%d>\r\n", port)
		fmt.Fprintf(&buf, "    ServerName %s\r\n", v.Domain)

		if v.ProxyPort > 0 {

			fmt.Fprintf(&buf, "    ProxyPreserveHost On\r\n")
			fmt.Fprintf(&buf, "    ProxyRequests Off\r\n")
			fmt.Fprintf(&buf, "    ProxyPass / http://127.0.0.1:%d/\r\n", v.ProxyPort)
			fmt.Fprintf(&buf, "    ProxyPassReverse / http://127.0.0.1:%d/\r\n", v.ProxyPort)
		} else {
			docroot := strings.ReplaceAll(ExpandPath(v.DocRoot, baseDir), `\`, `/`)
			fmt.Fprintf(&buf, "    DocumentRoot \"%s\"\r\n", docroot)
			fmt.Fprintf(&buf, "    <Directory \"%s\">\r\n", docroot)
			buf.WriteString("        Options Indexes FollowSymLinks\r\n")
			buf.WriteString("        AllowOverride All\r\n")
			buf.WriteString("        Require all granted\r\n")
			buf.WriteString("    </Directory>\r\n")
		}
		buf.WriteString("</VirtualHost>\r\n\r\n")
	}
	buf.WriteString(apacheMarkerEnd + "\r\n")
	return atomicWrite(path, buf.Bytes())
}

func writeNginxSites(dir, baseDir string, vhosts []Vhost) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if !e.IsDir() && strings.HasPrefix(e.Name(), "goampp-") {
			_ = os.Remove(filepath.Join(dir, e.Name()))
		}
	}

	for _, v := range vhosts {
		if v.ServerType != "" && v.ServerType != "nginx" && v.ServerType != "both" {
			continue
		}
		docroot := strings.ReplaceAll(ExpandPath(v.DocRoot, baseDir), `\`, `/`)
		port := v.Port
		if port == 0 {
			port = 80
		}
		var buf bytes.Buffer
		buf.WriteString("# Generated by GoAMPP.\r\n")
		fmt.Fprintf(&buf, "server {\r\n")
		fmt.Fprintf(&buf, "    listen %d;\r\n", port)
		fmt.Fprintf(&buf, "    server_name %s;\r\n", v.Domain)
		fmt.Fprintf(&buf, "    root %s;\r\n", docroot)
		buf.WriteString("    index index.php index.html;\r\n\r\n")
		buf.WriteString("    location / {\r\n        try_files $uri $uri/ /index.php?$query_string;\r\n    }\r\n\r\n")
		buf.WriteString("    location ~ \\.php$ {\r\n")
		buf.WriteString("        fastcgi_pass 127.0.0.1:9000;\r\n")
		buf.WriteString("        fastcgi_index index.php;\r\n")
		buf.WriteString("        include fastcgi_params;\r\n")
		buf.WriteString("        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\r\n")
		buf.WriteString("    }\r\n")
		buf.WriteString("}\r\n")

		path := filepath.Join(dir, "goampp-"+safeFileName(v.Domain)+".conf")
		if err := atomicWrite(path, buf.Bytes()); err != nil {
			return err
		}
	}
	return nil
}

func safeFileName(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '.', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func stripManagedBlock(src []byte, begin, end string) []byte {
	if len(src) == 0 {
		return src
	}
	var out bytes.Buffer
	sc := bufio.NewScanner(bytes.NewReader(src))

	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)

	inBlock := false
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == begin {
			inBlock = true
			continue
		}
		if trimmed == end {
			inBlock = false
			continue
		}
		if inBlock {
			continue
		}
		out.WriteString(line)
		out.WriteString("\r\n")
	}
	return out.Bytes()
}

func atomicWrite(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".goampp-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return err
	}

	_ = os.Remove(path)
	return os.Rename(tmpPath, path)
}
