//go:build windows

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Managed blocks in hosts file and vhost includes are delimited by these
// markers so we only touch lines we own. Hand-edited lines outside the block
// are preserved untouched.
const (
	hostsMarkerBegin = "# >>> GoAMPP managed hosts BEGIN — do not edit this block <<<"
	hostsMarkerEnd   = "# <<< GoAMPP managed hosts END >>>"

	apacheMarkerBegin = "# >>> GoAMPP managed Apache vhosts BEGIN <<<"
	apacheMarkerEnd   = "# <<< GoAMPP managed Apache vhosts END >>>"
)

// DefaultHostsFile returns the Windows hosts file path. Tests / advanced users
// can override via Config.Settings.HostsFile.
func DefaultHostsFile() string {
	sysRoot := os.Getenv("SystemRoot")
	if sysRoot == "" {
		sysRoot = `C:\Windows`
	}
	return filepath.Join(sysRoot, "System32", "drivers", "etc", "hosts")
}

// ApplyVhosts is the single entry point the UI calls after the user modifies
// the vhost list. It rewrites hosts + Apache vhost include + Nginx site files
// in one shot. Any single failure is returned without rolling back partial
// writes — the managed-block design means a retry is safe.
func ApplyVhosts(baseDir string, cfg *Config) error {
	enabled := make([]Vhost, 0, len(cfg.Vhosts))
	for _, v := range cfg.Vhosts {
		if v.Enabled {
			enabled = append(enabled, v)
		}
	}

	// 1. hosts file — needs admin. We try and bubble up the access error so
	// the UI can show a helpful "run as admin" hint.
	hostsPath := cfg.Settings.HostsFile
	if hostsPath == "" {
		hostsPath = DefaultHostsFile()
	} else {
		hostsPath = ExpandPath(hostsPath, baseDir)
	}
	if err := writeHostsBlock(hostsPath, enabled); err != nil {
		return fmt.Errorf("hosts file: %w", err)
	}

	// 2. Apache include
	if p := ExpandPath(cfg.Settings.ApacheVhostsInclude, baseDir); p != "" {
		if err := writeApacheVhosts(p, baseDir, enabled); err != nil {
			return fmt.Errorf("apache vhosts: %w", err)
		}
	}

	// 3. Nginx sites directory — one file per domain, easier for nginx -t
	// to pinpoint errors.
	if p := ExpandPath(cfg.Settings.NginxSitesDir, baseDir); p != "" {
		if err := writeNginxSites(p, baseDir, enabled); err != nil {
			return fmt.Errorf("nginx sites: %w", err)
		}
	}
	return nil
}

// writeHostsBlock reads the existing hosts file, strips any previous GoAMPP
// block, appends a fresh one, and writes atomically.
func writeHostsBlock(path string, vhosts []Vhost) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	cleaned := stripManagedBlock(existing, hostsMarkerBegin, hostsMarkerEnd)

	var buf bytes.Buffer
	buf.Write(cleaned)
	if len(cleaned) > 0 && !bytes.HasSuffix(cleaned, []byte("\n")) {
		buf.WriteString("\r\n")
	}
	buf.WriteString(hostsMarkerBegin + "\r\n")
	for _, v := range vhosts {
		// Every managed domain is pinned to 127.0.0.1. IPv6 loopback is also
		// emitted so browsers that prefer ::1 resolve correctly.
		fmt.Fprintf(&buf, "127.0.0.1 %s\r\n", v.Domain)
		fmt.Fprintf(&buf, "::1       %s\r\n", v.Domain)
	}
	buf.WriteString(hostsMarkerEnd + "\r\n")

	return atomicWrite(path, buf.Bytes())
}

// writeApacheVhosts rewrites one big include file with every enabled vhost
// as a <VirtualHost> block. The file is Include'd from httpd.conf by the
// Apache post-install hook.
//
// Apache 2.4 quirk: once *any* <VirtualHost *:80> exists, Apache stops
// using the main-scope DocumentRoot as the default for unmatched Host
// headers and falls back to the *first* VirtualHost block instead. So
// we ALWAYS emit a default `localhost` vhost as the first entry,
// serving the project-wide www/ directory. Hitting http://localhost/
// then shows the standard index while hitting http://myapp.test/ hits
// the named vhost that follows.
func writeApacheVhosts(path, baseDir string, vhosts []Vhost) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	defaultDocRoot := strings.ReplaceAll(
		filepath.Join(baseDir, "www"), `\`, `/`)

	var buf bytes.Buffer
	buf.WriteString(apacheMarkerBegin + "\r\n")
	buf.WriteString("# Generated by GoAMPP — edits inside this file will be overwritten.\r\n\r\n")

	// --- Default catch-all for http://localhost/ ---
	fmt.Fprintf(&buf, "<VirtualHost *:80>\r\n")
	fmt.Fprintf(&buf, "    ServerName localhost\r\n")
	fmt.Fprintf(&buf, "    DocumentRoot \"%s\"\r\n", defaultDocRoot)
	fmt.Fprintf(&buf, "    <Directory \"%s\">\r\n", defaultDocRoot)
	buf.WriteString("        Options Indexes FollowSymLinks\r\n")
	buf.WriteString("        AllowOverride All\r\n")
	buf.WriteString("        Require all granted\r\n")
	buf.WriteString("    </Directory>\r\n")
	buf.WriteString("</VirtualHost>\r\n\r\n")

	// --- Named vhosts for each user project ---
	for _, v := range vhosts {
		if v.ServerType != "" && v.ServerType != "apache" && v.ServerType != "both" {
			continue
		}
		if !v.Enabled {
			continue
		}
		port := v.Port
		if port == 0 {
			port = 80
		}

		fmt.Fprintf(&buf, "<VirtualHost *:%d>\r\n", port)
		fmt.Fprintf(&buf, "    ServerName %s\r\n", v.Domain)

		if v.ProxyPort > 0 {
			// Reverse-proxy mode for Node/Python/Go/Java dev
			// servers. Apache forwards every request to the
			// upstream port. The user runs `npm run dev` /
			// `flask run` themselves; we just route traffic.
			//
			// Requires mod_proxy + mod_proxy_http loaded in
			// httpd.conf — the Apache post-install enables both.
			fmt.Fprintf(&buf, "    ProxyPreserveHost On\r\n")
			fmt.Fprintf(&buf, "    ProxyRequests Off\r\n")
			fmt.Fprintf(&buf, "    ProxyPass / http://127.0.0.1:%d/\r\n", v.ProxyPort)
			fmt.Fprintf(&buf, "    ProxyPassReverse / http://127.0.0.1:%d/\r\n", v.ProxyPort)
		} else {
			docroot := strings.ReplaceAll(ExpandPath(v.DocRoot, baseDir), `\`, `/`)
			fmt.Fprintf(&buf, "    DocumentRoot \"%s\"\r\n", docroot)
			fmt.Fprintf(&buf, "    <Directory \"%s\">\r\n", docroot)
			buf.WriteString("        Options Indexes FollowSymLinks\r\n")
			buf.WriteString("        AllowOverride All\r\n")
			buf.WriteString("        Require all granted\r\n")
			buf.WriteString("    </Directory>\r\n")
		}
		buf.WriteString("</VirtualHost>\r\n\r\n")
	}
	buf.WriteString(apacheMarkerEnd + "\r\n")
	return atomicWrite(path, buf.Bytes())
}

// writeNginxSites writes one file per vhost into the sites directory. Any
// stale files that don't correspond to an active vhost get removed so Nginx
// doesn't keep serving a domain the user has disabled.
func writeNginxSites(dir, baseDir string, vhosts []Vhost) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	// Remove prior managed files (prefix-matched to avoid touching user files).
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if !e.IsDir() && strings.HasPrefix(e.Name(), "goampp-") {
			_ = os.Remove(filepath.Join(dir, e.Name()))
		}
	}

	for _, v := range vhosts {
		if v.ServerType != "" && v.ServerType != "nginx" && v.ServerType != "both" {
			continue
		}
		docroot := strings.ReplaceAll(ExpandPath(v.DocRoot, baseDir), `\`, `/`)
		port := v.Port
		if port == 0 {
			port = 80
		}
		var buf bytes.Buffer
		buf.WriteString("# Generated by GoAMPP.\r\n")
		fmt.Fprintf(&buf, "server {\r\n")
		fmt.Fprintf(&buf, "    listen %d;\r\n", port)
		fmt.Fprintf(&buf, "    server_name %s;\r\n", v.Domain)
		fmt.Fprintf(&buf, "    root %s;\r\n", docroot)
		buf.WriteString("    index index.php index.html;\r\n\r\n")
		buf.WriteString("    location / {\r\n        try_files $uri $uri/ /index.php?$query_string;\r\n    }\r\n\r\n")
		buf.WriteString("    location ~ \\.php$ {\r\n")
		buf.WriteString("        fastcgi_pass 127.0.0.1:9000;\r\n")
		buf.WriteString("        fastcgi_index index.php;\r\n")
		buf.WriteString("        include fastcgi_params;\r\n")
		buf.WriteString("        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\r\n")
		buf.WriteString("    }\r\n")
		buf.WriteString("}\r\n")

		path := filepath.Join(dir, "goampp-"+safeFileName(v.Domain)+".conf")
		if err := atomicWrite(path, buf.Bytes()); err != nil {
			return err
		}
	}
	return nil
}

// safeFileName strips characters that are unsafe in filenames so a domain
// like `foo:8080` doesn't blow up os.WriteFile on Windows.
func safeFileName(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '.', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// stripManagedBlock removes any previous begin/end delimited managed block
// from src, returning the rest verbatim. Line endings in src are preserved
// so we don't flip a whole file's EOL style as a side effect.
func stripManagedBlock(src []byte, begin, end string) []byte {
	if len(src) == 0 {
		return src
	}
	var out bytes.Buffer
	sc := bufio.NewScanner(bytes.NewReader(src))
	// The default scanner buffer (64KB) is too small for pathologically huge
	// hosts files. 1MB is plenty but still safe.
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)

	inBlock := false
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == begin {
			inBlock = true
			continue
		}
		if trimmed == end {
			inBlock = false
			continue
		}
		if inBlock {
			continue
		}
		out.WriteString(line)
		out.WriteString("\r\n")
	}
	return out.Bytes()
}

// atomicWrite writes to a temp file next to the target then renames. This
// way an interrupted write can't corrupt the existing file.
func atomicWrite(path string, data []byte) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".goampp-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return err
	}
	// os.Rename on Windows fails if the target exists, so remove it first.
	// Accept ENOENT — the target may legitimately not exist yet.
	_ = os.Remove(path)
	return os.Rename(tmpPath, path)
}
